name: Issue Template
description: Submit an issue
title: "ISSUE TITLE - CHANGE ME"
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        Please use the below form to submit an issue.
  - type: textarea
    id: Description
    attributes:
      label: Description
      description: Describe the issue
      placeholder: Tell us what's up
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Low (3), Normal (2), or High (1) priority
      options:
        - 3
        - 2
        - 1
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Due Date
      description: Please enter a due date for task completion in the form YYYY-MM-DD
      value: "YYYY-MM-DD"
    validations:
      required: true