name: totango

on:
  issues:
    types: [closed, labeled, edited]
  issue_comment:

jobs:
  totango-integration:
    # Prevent action from trying to parse issues that don't have a label which this action supports
    if: contains(github.event.issue.labels.*.name, 'task') ||
        contains(github.event.issue.labels.*.name, 'touchpoint')
    runs-on: ubuntu-latest
    steps:
      - name: Main run
        uses: jmassardo/issues-to-totango@VERSION
        with:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
          ACTIVITY_TYPE: ${{ vars.ACTIVITY_TYPE }}
          TOUCHPOINT_TAGS: ${{ vars.TOUCHPOINT_TAGS }}
          TOUCHPOINT_TYPE: ${{ vars.TOUCHPOINT_TYPE }}
          TASK_ASSIGNEE: ${{ vars.TASK_ASSIGNEE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
