name: CI
on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install Dependencies
      run: npm install
    - name: Install ncc
      run: npm i -g @vercel/ncc
    - name: Test
      run: npm test
    - name: Build
      run: ncc build src/index.js --license licenses.txt
